trigger:
  branches:
    exclude:
    - main
  paths:
    exclude:
    - '*'

pool:
  name: CloudVM

variables:
  currentDirectory: '$(System.DefaultWorkingDirectory)'

jobs:
- job: executeRepositoryScript
  condition: eq(variables['Build.Reason'], 'PullRequest')
  displayName: 'Execute Repository PowerShell Script'
  steps:
  - script: echo $(githubPat)
  - script: echo $(openAiGptPat)
  - task: PowerShell@2
    inputs:
      targetType: filePath
      filePath: './Scripts/validator.ps1'
      arguments: '-pull_number $(System.PullRequest.PullRequestNumber) -YOUR_PERSONAL_ACCESS_TOKEN $(githubPat) -GptApiKey $(openAiGptPat) -currentDirectory "$(currentDirectory)"'
