trigger:
  branches:
    exclude:
    - main
  paths:
    exclude:
    - '*'

pool:
  name: CloudVM
  # Specify the agent pool named 'CloudVM' for job execution.

variables:
  currentDirectory: '$(System.DefaultWorkingDirectory)'
  YOUR_PERSONAL_ACCESS_TOKEN: $(githubPat)  # Map the githubPat variable from the library.
  GptApiKey: $(openAiGptPat)  # Map the openAiGptPat variable from the library.
  # Define a pipeline variable 'currentDirectory' and set it to the default working directory.

jobs:
- job: executeRepositoryScript
  condition: eq(variables['Build.Reason'], 'PullRequest')
  # Define a job named 'executeRepositoryScript' that runs only when the build reason is a pull request.

  displayName: 'Execute Repository PowerShell Script'
  # Provide a human-readable name for the job.

  steps:
  - task: PowerShell@2
    inputs:
      targetType: filePath
      filePath: './Scripts/validator.ps1'
      # Run a PowerShell script file located at './Scripts/validator.ps1'.

      arguments: '-pull_number $(System.PullRequest.PullRequestNumber) -YOUR_PERSONAL_ACCESS_TOKEN $(YOUR_PERSONAL_ACCESS_TOKEN) -GptApiKey $(GptApiKey) -currentDirectory "$(currentDirectory)"'
      # Pass command-line arguments to the PowerShell script. Placeholders like $(System.PullRequest.PullRequestNumber), $(githubPat), and $(openAiGptPat) will be replaced with actual values during execution.
      # Also, include the current working directory as an argument.

      # This YAML code sets up a job that executes a PowerShell script when triggered by a pull request.
