# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: CloudVM

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- task: UiPathRunJob@3
  inputs:
    orchestratorConnection: 'UiPath Test Connection'
    processName: 'vajrang_logtime'
    folderName: 'Shared'
    strategy: 'Specific'
    robotsIds: 'laptop-k4bgskpc\yesav'