# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
# - main
 - pull_request

pool: CloudVM

steps:
- script: |
      echo $(Build.SourceVersion)
      set TestVar=$(Build.SourceVersion)
      set MyCustomVar=%TestVar:~0,7%
      echo %MyCustomVar%
- script: echo $(githubPat)
  displayName: 'Run a one-line script'

- powershell: |
    $fullSourceVersion  = "$(Build.SourceVersion)"
    $sourceVersion = $fullSourceVersion.Substring(0, 7)
    Write-Host "Truncated Source Version is $sourceVersion"
    
    $uri = "https://api.github.com/repos/vajrang-b/RPA-Developer-in-30-Days/commits/$sourceVersion"
    Write-Output $uri
    
    $headers = @{
      "Authorization" = "Bearer $($env:GITHUB_PAT)"
    }
    
    $response = Invoke-RestMethod -Uri $uri -Method GET -Headers $headers
    Write-Output $response.files
  displayName: 'Make HTTP Request with PowerShell'
  env:
    GITHUB_PAT: $(githubPat)

- task: PowerShell@2
         displayName: 'PowerShell Script'
         inputs:
           targetType: filePath
           filePath: './Scripts/validator.ps1'
  
# - task: UiPathRunJob@3
#   inputs:
#     orchestratorConnection: 'UiPath Test Connection'
#     processName: 'vajrang_logtime'
#     folderName: 'Shared'

- task: CmdLine@2
  condition: eq(variables['Build.Reason'], 'PullRequest')
  inputs:
    script: |
      echo Write your commands here
      echo Hello world
      echo $(System.PullRequest.PullRequestNumber)
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.      
      Write-Host "Hello World"

- task: GitHubComment@0
  condition: eq(variables['Build.Reason'], 'PullRequest')
  inputs:
    gitHubConnection: 'vajrang-b'
    repositoryName: 'vajrang-b/RPA-Developer-in-30-Days'
    id: $(System.PullRequest.PullRequestNumber)
    comment: 'Congratulations on creating a pr, your code will be reviewed soon'